version: '3.8'
services:
  mailsenderg:
    build: 
      context : .
      dockerfile : ./docker/Dockerfile
    container_name: MailSenderG
    tty: true
    ports:
      - "8200:3100"
    volumes:
      - ./:/go/src/MailSenderG